server:
  port: 3030
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/um
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: gmail.smtp.com
    port: 587
    username: maheshwar.4ever@gmail.com
    password: abc
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
app:
  messages:
    accLocked: Your account is Locked. Un-Lock your account first.
    loginSuccess: Login Successfull.
    invalidCredential: Credentials are invalid. Use valid credentials.
    success: Success...You got password in your email.
    fail: Wrong email!! Please check once again.
      